// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = 'https://rdnfavlcvlgvqhhogyth.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkbmZhdmxjdmxndnFoaG9neXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDE0OTUsImV4cCI6MjA3MjIxNzQ5NX0.A8WimjOuI4IDD8Con5IevX9cJhzC4bgVPU-xfMs4-nc';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});